# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  tests: true
  timeout: 10m
  modules-download-mode: readonly

linters: # use all linters that not deprecate, except some linters we do not like
  enable:
    # will use depguard when needed
    # - depguard
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - exhaustruct # force all struct field should be defined
    - gochecknoglobals # force no global var
    - goerr113 # force to use static error
    - lll # force line max char
    - nlreturn # force blank line above return
    - nonamedreturns
    - nosprintfhostport # force to use net.JoinHostPort
    - tagalign # force tag should be align
    - testpackage # force to use package_test format
    - varnamelen # force var name should not short
    - wrapcheck # force wrap error
    - wsl # does not understand what it does

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - dupl

linters-settings:
  goconst:
    min-occurrences: 10
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
