app:
  name: "string"
  version: "string"
  environment: "string"

http:
  host: "string"
  port: "string"

grpc:
  host: "string"
  port: "string"

logger:
  log_level: "string"

postgres:
  username: "string"
  password: "string"
  host: "string"
  port: "string"
  db_name: "string"

redis:
  host: "string"
  port: "string"

migration:
  auto: true
  required: true

ext_api:
  gocheck_grpc:
    host: "string"
    port: "string"
